Improve for nm6408
RC-MODULE/u-boot pull request #1
Opened 2022-07-26 14:26 UTC by anton-bondarev

Some patches for 'mc127-05' board

2022-08-02 12:06 UTC, nekromant requested changes
1. Не ясна мотивация всех этих изменений. 
2. Просьба разбить на небольшие changeset'ы по фукнциональному назначению и описать, что они делают.
3. Это все надо проверять на других чипах, чтобы понять не сломает ли это чего. Без п. выше это сделать проблематично.

2022-08-02 12:06 UTC, nekromant commented on arch/arm/dts/mc127-05.dts
> +				spi-max-frequency = <100000>;
Есть причина так занижать частоту?

2022-08-02 12:06 UTC, nekromant commented on board/rcm/mc127-05/mc127-05.c
> +		spiregs + SSP_CR1);
Не совсем понял, что тут происходит

2022-08-02 12:06 UTC, nekromant commented on board/rcm/mc127-05/mc127-05.c
> +void spl_edcl_enable(void)
Насколько помню, значение разрешения edcl на этом чипе берется с bootm ноги (надо проверить по РЭ). И принудительно включать в коде смысла большого нет. В продакшне работу edcl надо блокировать, т.к. это риск с т.з. безопасности.

2022-08-02 12:06 UTC, nekromant commented on drivers/spi/pl022_spi.c
> +#if defined(CONFIG_TARGET_1888TX018) || defined(CONFIG_TARGET_1888BM18) || defined(CONFIG_TARGET_1888BC048) || defined(CONFIG_ARCH_RCM_ARM)
Это точно надо на все ARM платы?

2022-08-02 12:27 UTC, anton-bondarev commented on board/rcm/mc127-05/mc127-05.c
> +		spiregs + SSP_CR1);
Ничего, просто форматирование, это теепрь под `#if 0`

2022-08-02 12:31 UTC, anton-bondarev commented on board/rcm/mc127-05/mc127-05.c
> +void spl_edcl_enable(void)
Тут на самом деле ставится бит в сетеухе (GRETH) который разрешает прием по этому протоколу. То есть где смотреть не важно, смотрим на bootm и вызываем эту функцию. Но согласен, что может перенести в сетевуху стоит.

2022-08-05 19:13 UTC, nekromant commented on board/rcm/mc127-05/mc127-05.c
> +void spl_edcl_enable(void)
Значение этого бита при старте берется с bootm насколько помню.

2022-08-17 09:51 UTC, closed without merging